apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nx.name }}
  namespace: {{ .Values.nx.namespace }}
spec:
  type: LoadBalancer
  selector:
    name: {{ .Values.nx.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.nx.containerPort }}
    targetPort: {{ .Values.nx.containerPort }}