apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wp.name }}-secret
  namespace: {{ .Values.wp.namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.wp.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
